# Generated by Django 3.2.6 on 2021-12-17 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otrender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiontimes',
            name='time',
            field=models.TimeField(),
        ),
    ]
