# Generated by Django 3.2.6 on 2021-08-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otrender', '0002_auto_20210811_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='sessiondates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='sessionTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='tutorGroup',
            field=models.CharField(default='0000', max_length=4),
        ),
        migrations.DeleteModel(
            name='session',
        ),
    ]
