# Generated by Django 3.2.6 on 2021-12-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otrender', '0002_alter_sessiondates_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiontimes',
            name='time',
            field=models.TimeField(unique=True),
        ),
    ]
