# Generated by Django 3.2.6 on 2021-12-19 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otrender', '0004_alter_sessiontimes_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiondates',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
