# Generated by Django 3.2.6 on 2022-02-14 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otrender', '0005_alter_sessiondates_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username']},
        ),
    ]
